MAIN:
    MOV DPTR, #competitors
    CLR A
    MOVC A, @A+DPTR
    MOV B, A
    MOV R0, #15

NEXT_NUMBER:
    INC DPTR
    CLR A
    MOVC A, @A+DPTR

    PUSH ACC
    MOV A, B
    PUSH ACC

    POP ACC
    JNB ACC.7, B_POSITIVE

    POP ACC
    JNB ACC.7, A_POSITIVE

    CJNE A, B, CHECK_CY
    SJMP DONE_COMPARE

A_POSITIVE:
    MOV B, A
    SJMP DONE_COMPARE

B_POSITIVE:
    POP ACC
    JB ACC.7, B_LARGER

    CJNE A, B, CHECK_CY
    SJMP DONE_COMPARE

CHECK_CY:
    JC B_LARGER
    MOV B, A

DONE_COMPARE:
    DJNZ R0, NEXT_NUMBER
    JMP $

B_LARGER:
    SJMP DONE_COMPARE

competitors:
DB 27H,0A7H,9AH,64H,3BH,71H,89H,0C5H
DB 4BH,5BH,82H,0DEH,9DH,7AH,6FH,0FEH